runtime: php55
api_version: 1

handlers: 
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /(.*\.(gif|png|jpg))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$

- url: /en
  script: /en/index.php

- url: /jp
  script: /jp/index.php

- url: /
  script: index.php
